"""AML Monitor — Alert model.

Созданные алерты: правило-триггер/ML-скор, transaction_id(s), severity, status.
"""

from __future__ import annotations

from decimal import Decimal

from sqlalchemy import Enum, ForeignKey, Numeric, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class Alert(TimestampMixin, Base):
    """An alert generated by a rule or ML model."""

    __tablename__ = "alerts"

    transaction_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("transactions.id"), nullable=True, index=True
    )

    rule_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("rules.id"), nullable=True, index=True
    )

    case_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("cases.id"), nullable=True, index=True
    )

    severity: Mapped[str] = mapped_column(
        Enum("low", "medium", "high", "critical", name="alert_severity"),
        nullable=False,
        default="medium",
    )

    risk_score: Mapped[Decimal | None] = mapped_column(
        Numeric(5, 2), default=Decimal("0.00")
    )
    """0.00–100.00 risk score."""

    title: Mapped[str] = mapped_column(String(512), nullable=False)
    """Human-readable alert title."""

    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    """Explainability text — why this alert was created."""

    status: Mapped[str] = mapped_column(
        Enum("new", "in_review", "escalated", "closed", name="alert_status"),
        nullable=False,
        default="new",
    )

    # Relationships
    transaction = relationship("Transaction", lazy="selectin")
    rule = relationship("Rule", lazy="selectin")
    case = relationship("Case", back_populates="alerts", lazy="selectin")